steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "ai/Dockerfile"
      - "-t"
      - "asia.gcr.io/$PROJECT_ID/aka-ai-api-service-image:latest"
      - "."
images:
  - "asia.gcr.io/$PROJECT_ID/aka-ai-api-service-image:latest"
options:
  machineType: E2_HIGHCPU_8
